SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--DROP DATABASE METADATA_FOOTBALL
GO
--CREATE DATABASE METADATA_FOOTBALL

GO

USE METADATA_FOOTBALL
GO

/*
	DELETE ALL TABLES AND CONSTRAINTS
*/
DECLARE @Sql NVARCHAR(500) 
DECLARE @Cursor CURSOR

SET @Cursor = CURSOR FAST_FORWARD FOR
SELECT DISTINCT sql = 'ALTER TABLE [' + tc2.TABLE_SCHEMA + '].[' +  tc2.TABLE_NAME + '] \
					   DROP [' + rc1.CONSTRAINT_NAME + '];'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC1 
	 LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC2 
	 ON TC2.CONSTRAINT_NAME =RC1.CONSTRAINT_NAME

OPEN @Cursor FETCH NEXT FROM @Cursor INTO @Sql

WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXEC sp_executesql @Sql
	FETCH NEXT FROM @Cursor INTO @Sql
END

CLOSE @Cursor DEALLOCATE @Cursor
GO

EXEC sp_MSforeachtable 'DROP TABLE ?'
GO


CREATE TABLE [DATA_FLOW_DDS] (
  [table_id] INT IDENTITY(1,1) NOT NULL,
  [table_name] VARCHAR(50) NOT NULL,
  [lset] datetime,
  CONSTRAINT [PK_DATA_FLOW_DDS] PRIMARY KEY ([table_id]),
)


INSERT INTO [DATA_FLOW_DDS] ([table_name],[lset] ) 
VALUES 
('DIM_Team', '1800-01-01 20:00:00'),
('DIM_League', '1800-01-01 20:00:00'),
('DIM_Season', '1800-01-01 20:00:00')

